# Generated by Django 2.1.2 on 2018-11-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['submission', 'testcase']},
        ),
    ]
