# Generated by Django 2.1.2 on 2018-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[(None, 'Choose Difficulty Level'), ('Unknown', 'Unknown'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=15, verbose_name='Difficulty level'),
        ),
    ]
