# Generated by Django 2.1.2 on 2018-11-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('questions', '0002_auto_20181119_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, help_text='Keep questions inactive until their contests start!', verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='question',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contests.Contest'),
        ),
    ]
