# Generated by Django 2.1.2 on 2018-12-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20181213_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
