# Generated by Django 2.1.2 on 2018-11-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181117_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no_of_views',
            field=models.IntegerField(null=True, verbose_name='Views count'),
        ),
    ]
