# Generated by Django 2.1.2 on 2018-10-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_auto_20181023_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('PY', 'Python2'), ('PY3', 'Python3')], max_length=5)),
                ('code', models.FileField(upload_to=questions.models.get_code_upload_url)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
