# Generated by Django 2.1.2 on 2018-11-18 14:58

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181118_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.back_image_upload_url),
        ),
    ]
