# Generated by Django 2.1.2 on 2018-11-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181117_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
