# Generated by Django 2.1.2 on 2018-11-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181122_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='Keep questions inactive until their contests start!', verbose_name='Is Active?'),
        ),
    ]
