# Generated by Django 2.1.2 on 2018-11-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_submission_attempt_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['question', 'user', 'submitted_on']},
        ),
    ]
