# Generated by Django 2.1.2 on 2018-11-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20181122_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-create_timestamp']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='contest',
        ),
    ]
