# Generated by Django 2.1.2 on 2018-12-09 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181123_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0, 'The score can not be negative'), django.core.validators.MaxValueValidator(100.0, 'Total Score must be calculated as a percentage of 100')]),
        ),
    ]
