# Generated by Django 2.1.2 on 2018-11-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181117_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='0', max_length=5, verbose_name='Difficulty level'),
        ),
    ]
