# Generated by Django 2.1.2 on 2018-10-28 12:16

import django.core.validators
from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181023_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FileField(upload_to=questions.models.get_testcase_output_upload_path, validators=[django.core.validators.FileExtensionValidator(['txt'], message='Only text files are allowed as input and output')], verbose_name='File Containing Expected Output'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('testcase', 'submission')},
        ),
    ]
