# Generated by Django 2.1.2 on 2018-11-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20181117_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='no_of_views',
            field=models.IntegerField(default='0', null=True, verbose_name='Views count'),
        ),
    ]
