# Generated by Django 2.1.2 on 2018-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20181206_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
