# Generated by Django 2.1.2 on 2018-10-28 13:43

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_result_error_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='error_file',
            field=models.FileField(upload_to=questions.models.get_error_upload_url),
        ),
    ]
