# Generated by Django 2.1.2 on 2018-11-17 07:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_auto_20181117_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='attempt_number',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('question', 'user', 'attempt_number')},
        ),
    ]
