# Generated by Django 2.1.2 on 2018-11-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_auto_20181117_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_view_count', models.IntegerField(verbose_name='Question View Count')),
                ('submissions_count', models.IntegerField(verbose_name='Submission Count')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='no_of_views',
        ),
        migrations.AddField(
            model_name='statistics',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
