# Generated by Django 2.1.2 on 2018-11-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0009_auto_20181117_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='question',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Question View Count'),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.AddField(
            model_name='questionview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='question'),
        ),
        migrations.AddField(
            model_name='questionview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
