# Generated by Django 2.1.2 on 2018-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181028_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='error_file',
        ),
        migrations.AddField(
            model_name='result',
            name='errors',
            field=models.TextField(blank=True),
        ),
    ]
