# Generated by Django 2.1.2 on 2018-11-17 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181117_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
