# Generated by Django 2.1.2 on 2018-11-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_question_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='create_time',
            new_name='create_timestamp',
        ),
    ]
