# Generated by Django 2.1.2 on 2018-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20181118_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='create_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
