# Generated by Django 2.1.2 on 2018-11-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181118_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
