# Generated by Django 2.1.2 on 2018-10-28 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181028_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='pass_fail',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='0 : Unknown Result, 1:Correct Answer,                                     2: Timeout, 3:Runtime Error, 4:In Progress', validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
