# Generated by Django 2.1.2 on 2018-11-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20181117_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='0', max_length=15, verbose_name='Difficulty level'),
        ),
    ]
