# Generated by Django 2.1.2 on 2018-10-28 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20181028_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.FloatField(help_text='This is approx the time limit that will be required to run a python code                                       for the problem. This limit will be automatically reduced for other languages                                       like C which take much lesser time for similar implementation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10, 'We currently do not allow any                                    code that runs for more than 10 secs')], verbose_name='Time Limit'),
        ),
        migrations.AlterField(
            model_name='result',
            name='pass_fail',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='0 : Unknown Result, 1:Correct Answer,                                     2: Timeout, 3:Runtime Error, 4:Wrong Answer, 5:In progress', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
