# Generated by Django 2.1.2 on 2018-10-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20181028_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='input_file',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='output',
            new_name='output_file',
        ),
    ]
