# Generated by Django 2.1.2 on 2018-11-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20181117_1318'),
        ('questions', '0015_auto_20181117_2309'),
    ]

    operations = [
    ]
