# Generated by Django 2.1.2 on 2018-11-17 18:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0016_merge_20181117_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('question', 'user')},
        ),
    ]
