# Generated by Django 2.1.2 on 2018-11-01 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20181031_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0, 'The score can not be negative'), django.core.validators.MaxValueValidator(100.0, 'Total Score must be calculated as a percentage of 100')]),
        ),
    ]
