# Generated by Django 2.1.2 on 2018-11-17 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0017_auto_20181117_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('question', 'user', 'attempt_number')},
        ),
    ]
