# Generated by Django 2.1.2 on 2018-11-01 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20181101_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.TextField(default='Sample short description', help_text='A short description whch describes your question. This will be visible when                                          user hovers on your question the all questions page', max_length=250, verbose_name='Short Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.FloatField(default=2.0, help_text='This is approx the time limit that will be required to run a python code                                       for the problem. This limit will be automatically reduced for other languages                                       like C which take much lesser time for similar implementation', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10, 'We currently do not allow any                                    code that runs for more than 10 secs')], verbose_name='Time Limit'),
        ),
    ]
