# Generated by Django 2.1.2 on 2018-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20181101_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.ManyToManyField(to='questions.Catagory', verbose_name='Catagories'),
        ),
    ]
