# Generated by Django 2.1.2 on 2018-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20181104_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='constraints',
            field=models.TextField(null='True', verbose_name='Constraints'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='question',
            name='input_format',
            field=models.TextField(null='True', verbose_name='Input format'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='question',
            name='output_format',
            field=models.TextField(null='True', verbose_name='Output format'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input',
            field=models.TextField(null='True', verbose_name='Sample input'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output',
            field=models.TextField(null='True', verbose_name='Sample output'),
            preserve_default='True',
        ),
    ]
