# Generated by Django 2.1.2 on 2018-11-03 19:55

import django.core.validators
from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20181104_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_file',
            field=models.FileField(help_text='Upload a .txt file that contains the input for this test case', upload_to=questions.models.get_testcase_input_upload_path, validators=[django.core.validators.FileExtensionValidator(['txt'], message='Only text files are allowed as input and outpur')], verbose_name='File Containing Input'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_file',
            field=models.FileField(help_text='Upload a .txt file that contains the expected output for the above given input', upload_to=questions.models.get_testcase_output_upload_path, validators=[django.core.validators.FileExtensionValidator(['txt'], message='Only text files are allowed as input and output')], verbose_name='File Containing Expected Output'),
        ),
    ]
