# Generated by Django 2.1.2 on 2018-11-08 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20181104_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Number : '),
            preserve_default=False,
        ),
    ]
