# Generated by Django 2.1.2 on 2018-11-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_testcase_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('question', 'number')},
        ),
    ]
