# Generated by Django 2.1.2 on 2018-11-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20181109_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edited On'),
        ),
    ]
