# Generated by Django 2.1.2 on 2018-11-17 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Notification content', max_length=250, verbose_name='content')),
                ('icon', models.CharField(max_length=50, verbose_name='icon')),
                ('link', models.URLField(verbose_name='link')),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time_stamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-time_stamp'],
            },
        ),
    ]
