# Generated by Django 2.1.2 on 2018-12-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='About User'),
        ),
    ]
