# Generated by Django 2.1.2 on 2018-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20181119_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time_stamp'),
        ),
    ]
