# Generated by Django 2.1.2 on 2018-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20181214_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(help_text='USE ONLY NAME. NOT FULL TEXT', max_length=200, verbose_name='link'),
        ),
    ]
