# Generated by Django 2.1.2 on 2018-11-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20181119_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(help_text='USE ONLY NAME. NOT FULL TEXT', max_length=50, verbose_name='link'),
        ),
    ]
