# Generated by Django 2.0.9 on 2018-12-08 09:31

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20181119_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='/profiles/default.png', upload_to=registration.models.get_profile_picture_upload_path),
        ),
    ]
