# Generated by Django 2.0.9 on 2018-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_userprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(max_length=500, null=True, verbose_name='About User'),
        ),
    ]
