# Generated by Django 2.1.2 on 2018-12-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
    ]
