# Generated by Django 2.0.9 on 2018-12-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contacts',
            field=models.CharField(help_text='Give your email, phone etc. so that people can contact you if they need to', max_length=200, null=True),
        ),
    ]
