# Generated by Django 2.1.2 on 2018-12-12 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
