# Generated by Django 2.0.9 on 2018-12-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20181212_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='eligibility',
            field=models.TextField(help_text='What is the eligibility criteria for participants?', null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='prizes',
            field=models.TextField(help_text='Mention prizes for diff positions/winners (If any)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=models.TextField(help_text='What are the rules that all participants must follow?', null=True),
        ),
    ]
