# Generated by Django 2.1.2 on 2018-11-23 17:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181123_2240'),
        ('contests', '0002_auto_20181122_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='unique_code',
            field=models.CharField(db_index=True, default='test001contest', help_text="A unique code for your contest. between 3-15 characters. May contain only                                       lowercase characters and numbers. For example if the question name is 'Sorting Array',                                       you may name the code SORTARR", max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[0-9a-z]*$', 'The Unique code can contain only small case alphabets and numbers ')], verbose_name='Unique Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contestquestion',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='contestquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
