# Generated by Django 2.1.2 on 2018-12-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_remove_contest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_active',
            field=models.IntegerField(default=True, help_text='-1 for yet to start, 0 for in progress,                                         1 for completed'),
        ),
    ]
