# Generated by Django 2.1.2 on 2018-12-13 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20181212_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(related_name='participating_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
