# Generated by Django 2.0.9 on 2018-12-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20181212_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contacts',
            field=models.TextField(help_text='Give your email, phone etc. so that people can contact you if they need to', null=True),
        ),
    ]
