# Generated by Django 2.0.9 on 2018-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20181123_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='short_description',
            field=models.TextField(help_text='A short description whch describes your contest.', max_length=250, null=True, verbose_name='Short Description'),
        ),
    ]
