# Generated by Django 2.1.2 on 2018-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20181210_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.IntegerField(default=-1, help_text='-1 for yet to start, 0 for in progress,                                         1 for completed'),
        ),
    ]
