# Generated by Django 2.0.9 on 2018-12-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contacts',
            field=models.EmailField(help_text='Give your email, phone etc. so that people can contact you if they need to', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='eligibility',
            field=models.CharField(help_text='What is the eligibility criteria for participants?', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='prizes',
            field=models.CharField(help_text='Mention prizes for diff positions/winners (If any)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=models.CharField(help_text='What are the rules that all participants must follow?', max_length=200, null=True),
        ),
    ]
