# Generated by Django 2.0.9 on 2018-12-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20181202_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateField(verbose_name='End Date Time'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateField(verbose_name='Start Date Time'),
        ),
    ]
