# Generated by Django 2.1.2 on 2018-12-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_is_active'),
        ('contests', '0008_auto_20181203_0058'),
    ]

    operations = [
    ]
