# Generated by Django 2.1.2 on 2018-12-08 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20181123_2240'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0009_merge_20181207_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestLiveSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8)),
                ('timedelta', models.PositiveIntegerField(editable=False)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='ContestQuestionTopSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestQuestion')),
                ('contestsubmission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestLiveSubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contestquestiontopsubmission',
            unique_together={('user', 'contest_question')},
        ),
    ]
