# Generated by Django 2.0.9 on 2018-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_merge_20181207_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.IntegerField(default=0, help_text='0 for yet to start, 1 for in progress,                                         2 for completed'),
        ),
    ]
