# Generated by Django 2.1.2 on 2018-12-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20181209_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestlivesubmission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='contestlivesubmission',
            name='timedelta',
            field=models.PositiveIntegerField(),
        ),
    ]
