# Generated by Django 2.1.2 on 2018-12-09 04:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20181209_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_active',
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.IntegerField(default=0, help_text='0-Yet to start, 1- live, 2- ended', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
